### PR TITLE
Update fence_pre_attrs.js for mermaid language

### PR DESCRIPTION
**Pull request by Villyli**
update fense render for support mermaid.js in md

## Type of Change

- **Build Scripts:**  fence_pre_attrs.js 
- **Something else:** support mermaid language in `code` with  `environment-local` as default style

## What issue does this relate to?
- `mermaid` language code is not supported yet

### What should this PR do?
- add a mermaid interpreter for markdown-it in fence_pre_attrs.js (simply by add class)
- add mermaid default style as `environment-local` for a wrap container instead of original code default dark style
> provide just like:

image

> mermaid code:
```mermaid
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
 
```
**must add mermaid as js or module**
personally recomanded:  [https://www.jsdelivr.com/package/npm/mermaid](https://www.jsdelivr.com/package/npm/mermaid)

**TODO:**
- make a full markdown-it render for combine existing features like `label`,other `environment` style ...

### What are the acceptance criteria?
- Need add mermaid, the simpliest way : [https://www.jsdelivr.com/package/npm/mermaid](https://www.jsdelivr.com/package/npm/mermaid)
- Need to run npm test on local before this pr is approved.

### CODE REVIEW

**Comment by MattIPv4** [comment]
👋 Please could you explain why this is not possible using the existing functionality in do-markdownit?

**Comment by MattIPv4** [comment]
This change as it stands is not going to be merged, I do not wish to add a branch specifically for mermaid in here that bypasses all the existing functionality of the `fence_pre_attrs` plugin.

**Comment by MattIPv4** [comment]
It seems it is very possible to use do-markdownit as it stands to have a code block generated with the mermaid class on it:

```js
const md = require('markdown-it')({ langPrefix: '' })
    .use(require('.'), {
        fence_label: false,
        fence_environment: {
            allowedEnvironments: [ 'local' ],
        },
        fence_pre_attrs: false,
        prismjs: false,
    });

console.log(md.render('```mermaid\n[environment local]\ngraph TD\n    A --> B\n```'));
```

```html
<pre><code class="environment-local mermaid">graph TD
    A --&gt; B
</code></pre>
```

You can enable `fence_pre_attrs` too if you'd prefer the classes on the `pre` instead:

```
<pre class="environment-local mermaid"><code>graph TD
    A --&gt; B
</code></pre>
```

_However_, if you enable `prismjs` for syntax highlighting on code blocks, that will interfere with things as it will use the language set on the code block to drive its dedicated language class:

```
<pre class="environment-local language-mermaid"><code><span class="token keyword">graph</span> TD
    A <span class="token arrow operator">--&gt;</span> B
</code></pre>
```

Though if you enable `prismjs` but disable `fence_pre_attrs` you will get the original mermaid class still:

```
<pre class="language-mermaid"><code class="environment-local mermaid"><span class="token keyword">graph</span> TD
    A <span class="token arrow operator">--&gt;</span> B
</code></pre>
```

All that to say, I would appreciate a much more thorough description of exactly what situation you're running into that doesn't work currently that you're trying to solve for, and then we can look at how we can build a generic solution to that rather than hastily hard-coding a branch for mermaid.

**Comment by Villyli** [comment]
I agree hard-coding or put it in `fence_pre_attrs.js` is not a graceful way, just thought a PR has much sincerity than a ISSUE. I'm not a PM : )

In my case, I'm building both a live editor(with editor and previewer, just like digitalocean website has) and a markdown auto-render form-element(contents may generate by code to bulid various contents) used in form.

By adjusting config(`lang-prefix:''` and disable `fence_pre_attrs prismjs`) for markdown-it or do-markdownit, it can render markdown like you provide case 1. 
```html
<pre><code class="environment-local mermaid">graph TD
    A --&gt; B
</code></pre>
```
In fact, **mermaid can't out-boxes html elements**(`<code>`,`<span>`) in mermaid code which would led to **Syntax error in mermaid**. So case 2,3,4 in latest comment wouldn't work actually or something I don't know to config?

**Adjusting config** is also a global config for all markdown elements and feels like it's a hard-coding outside rather than inside. If I want to keep styles like  `fence_pre_attrs prismjs`, I don't want to have a two markdown render separately and handle mermaid code and other codes in markdown by myself. A default mermaid support is necessary for do-markdownit i thought.

Maybe provide a `origin` attr for user, or even `disable-*` attr for not using some of global configured in  specific code

**Comment by MattIPv4** [comment]
An issue probably would've been better here to actually discuss the problem + desired fix, rather than just opening a haphazard PR.

To clarify your ask here, you want to keep `fence_pre_attrs` enabled and also `prismjs`, so that most of your code blocks work as would normally be the case in do-markdownit, _but_ for Mermaid codeblocks specifically, you want to have Prism not run on them, and for the `mermaid` class to stay on the `code` element and not be moved by `fence_pre_attrs`?

So, what you're asking for, assuming that's the case, is a way to exclude specific languages from the `prismjs` plugin, and a way to exclude specific classes from `fence_pre_attrs`?

**Comment by Villyli** [comment]
Because not all author always keep passion or have time in open-source module like u, i worry it will be a long time for next fix so I provide my simple way fix it temporarily until next fix.

YES, I mean a way to exclude specific languages from the prismjs plugin, and a way to exclude specific classes from fence_pre_attrs. 

After that may need test if `[label ]` works as I supposed it should be. `[label ]` doesn't hinder code areas

**Comment by MattIPv4** [comment]
I leave it with you then to add the logic to handle those exclusions -- the exclusion for `prismjs` should be simple enough, but the exclusion for `fence_pre_attrs` might be a bit more complex as it's handling all attributes, not just classes.

Do you want to leave this PR open and work on those changes in this, or would it be better off starting afresh once you've got the changes ready in a new PR?

**Comment by Villyli** [comment]
I close this PR first

**Pull request closed without merging**
